import json
import shutil
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any
from src.loki.engine.sandbox import IncidentReport
from src.loki.engine.html_reporter import HTMLReporter
from src.loki.engine.scrubber import NetworkScrubber


class IncidentReporter:
    """Persists crash evidence and synthesizes automated reproduction scripts and HTML reports."""

    def __init__(self, base_output_dir: str = ".loki/runs"):
        self.base_output_dir = Path(base_output_dir)

    def save_session(
        self,
        report: IncidentReport,
        rules_evaluations: Optional[List[Dict[str, Any]]] = None,
    ) -> Path:
        """Saves a complete test execution session bundle with HTML report and video."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_dir = self.base_output_dir / f"run_{timestamp}"
        run_dir.mkdir(parents=True, exist_ok=True)

        # 1. Relocate recorded video to the incident directory
        final_video_file = None
        if report.video_path and Path(report.video_path).exists():
            dest_video = run_dir / "replay.webm"
            shutil.move(report.video_path, dest_video)
            final_video_file = "replay.webm"

        # 2. Relocate and scrub recorded network trace (HAR)
        final_har_file = None
        if report.har_path and Path(report.har_path).exists():
            dest_har = run_dir / "network.har"
            scrubbed = NetworkScrubber.scrub_har_file(Path(report.har_path), dest_har)
            if scrubbed and dest_har.exists():
                final_har_file = "network.har"
            try:
                Path(report.har_path).unlink(missing_ok=True)
            except Exception:
                pass

        # 3. Save incident metadata in incident.json
        metadata = {
            "run_id": run_dir.name,
            "timestamp": datetime.now().isoformat(),
            "target_url": report.target_url,
            "persona": report.persona_name,
            "duration_seconds": report.duration_seconds,
            "unique_crashes_count": len(set(report.crashes)),
            "crashes": list(set(report.crashes)),
            "http_errors": report.http_errors,
            "console_errors_count": len(report.console_errors),
            "actions_executed_count": len(report.actions_taken),
            "actions_taken": report.actions_taken,
            "rules_evaluations": rules_evaluations or [],
            "video_file": final_video_file,
            "har_file": final_har_file,
        }

        with open(run_dir / "incident.json", "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2)

        # 3. Generate the standalone Playwright reproduction test if crashes occurred
        if report.has_crashes:
            repro_code = self._generate_repro_script(report)
            with open(run_dir / "repro_test.py", "w", encoding="utf-8") as f:
                f.write(repro_code)

        # 4. Generate the standalone HTML report
        html_file = run_dir / "report.html"
        HTMLReporter.generate(metadata, html_file)

        return run_dir

    def save_incident(
        self,
        report: IncidentReport,
        rules_evaluations: Optional[List[Dict[str, Any]]] = None,
    ) -> Optional[Path]:
        """Creates an incident bundle if crashes or HTTP errors were detected."""
        if not report.has_crashes:
            return None
        return self.save_session(report, rules_evaluations)

    def _generate_repro_script(self, report: IncidentReport) -> str:
        """Synthesizes a minimal standalone Python script reproducing the crash."""
        return f'''"""
Auto-generated by LOKI Agent
Deterministic Crash Reproduction Script
Target: {report.target_url}
Persona: {report.persona_name}
"""

import sys
from playwright.sync_api import sync_playwright

def test_reproduce_crash():
    print("⚡ [LOKI REPRO] Starting deterministic crash verification...")
    detected_errors = []

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()

        # Listen for the exact crash
        page.on("pageerror", lambda err: detected_errors.append(str(err)))

        print("⚡ [LOKI REPRO] Navigating to target: {report.target_url}")
        page.goto("{report.target_url}", wait_until="domcontentloaded")

        print("⚡ [LOKI REPRO] Simulating rapid burst interaction...")
        buttons = page.query_selector_all("button:visible, input[type=\'submit\']:visible")
        for btn in buttons:
            try:
                for _ in range(5):
                    btn.click(timeout=1000, no_wait_after=True)
            except Exception:
                pass

        page.wait_for_timeout(1000)
        browser.close()

    if detected_errors:
        print("\\n💥 [LOKI REPRO] CRASH SUCCESSFULLY REPRODUCED!")
        for err in set(detected_errors):
            print(f"  • {{err}}")
        sys.exit(1)
    else:
        print("\\n✔ [LOKI REPRO] No crashes detected. Bug might be resolved.")
        sys.exit(0)

if __name__ == "__main__":
    test_reproduce_crash()
'''