import json
import shutil
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any
from src.loki.engine.sandbox import IncidentReport
from src.loki.engine.html_reporter import HTMLReporter
from src.loki.engine.scrubber import NetworkScrubber


class IncidentReporter:
    """Persists crash evidence and synthesizes automated reproduction scripts and HTML reports."""

    def __init__(self, base_output_dir: str = ".loki/runs"):
        self.base_output_dir = Path(base_output_dir)

    def save_session(
        self,
        report: IncidentReport,
        rules_evaluations: Optional[List[Dict[str, Any]]] = None,
    ) -> Path:
        """Saves a complete test execution session bundle with HTML report and video."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_dir = self.base_output_dir / f"run_{timestamp}"
        run_dir.mkdir(parents=True, exist_ok=True)

        # 1. Relocate recorded video to the incident directory
        final_video_file = None
        if report.video_path and Path(report.video_path).exists():
            dest_video = run_dir / "replay.webm"
            shutil.move(report.video_path, dest_video)
            final_video_file = "replay.webm"

        # 2. Relocate and scrub recorded network trace (HAR)
        final_har_file = None
        if report.har_path and Path(report.har_path).exists():
            dest_har = run_dir / "network.har"
            scrubbed = NetworkScrubber.scrub_har_file(Path(report.har_path), dest_har)
            if scrubbed and dest_har.exists():
                final_har_file = "network.har"
            try:
                Path(report.har_path).unlink(missing_ok=True)
            except Exception:
                pass

        # 3. Save incident metadata in incident.json
        metadata = {
            "run_id": run_dir.name,
            "timestamp": datetime.now().isoformat(),
            "target_url": report.target_url,
            "persona": report.persona_name,
            "device": report.device_name,
            "orientation": report.orientation,
            "duration_seconds": report.duration_seconds,
            "unique_crashes_count": len(set(report.crashes)),
            "crashes": list(set(report.crashes)),
            "http_errors": report.http_errors,
            "layout_issues": report.layout_issues,
            "console_errors_count": len(report.console_errors),
            "actions_executed_count": len(report.actions_taken),
            "actions_taken": report.actions_taken,
            "replay_trace": report.replay_trace,
            "rules_evaluations": rules_evaluations or [],
            "video_file": final_video_file,
            "har_file": final_har_file,
        }

        with open(run_dir / "incident.json", "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2)

        # 3. Generate the standalone Playwright reproduction test if crashes occurred
        if report.has_crashes:
            repro_code = self._generate_repro_script(report)
            with open(run_dir / "repro_test.py", "w", encoding="utf-8") as f:
                f.write(repro_code)

        # 4. Generate the standalone HTML report
        html_file = run_dir / "report.html"
        HTMLReporter.generate(metadata, html_file)

        return run_dir

    def save_incident(
        self,
        report: IncidentReport,
        rules_evaluations: Optional[List[Dict[str, Any]]] = None,
    ) -> Optional[Path]:
        """Creates an incident bundle if crashes or HTTP errors were detected."""
        if not report.has_crashes:
            return None
        return self.save_session(report, rules_evaluations)

    def _generate_repro_script(self, report: IncidentReport) -> str:
        """Synthesizes a minimal standalone Python script reproducing the crash."""
        if report.device_name:
            device_setup = f"""        device_desc = p.devices.get("{report.device_name}")
        if device_desc:
            print("📱 [LOKI REPRO] Emulating device: {report.device_name} ({report.orientation})")
            context = browser.new_context(**device_desc)
        else:
            context = browser.new_context()
        page = context.new_page()"""
        else:
            device_setup = """        context = browser.new_context()
        page = context.new_page()"""

        # repr() produces a valid Python literal (proper quoting/escaping) we can embed
        # directly as source, so the standalone script needs no extra parsing step.
        trace_literal = repr(report.replay_trace)

        return f'''"""
Auto-generated by LOKI Agent
Deterministic Crash Reproduction Script
Target: {report.target_url}
Persona: {report.persona_name}
Device: {report.device_name or 'Desktop'} ({report.orientation})
"""

import sys

# Ensure UTF-8 output encoding across Windows and POSIX
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

from playwright.sync_api import sync_playwright

# Structured trace of the concrete actions taken during the original chaos session
# (clicks, fills, network drops...). Empty when the persona/mode did not record one,
# in which case a generic fallback interaction is used instead.
REPLAY_TRACE = {trace_literal}


def replay_trace(page, trace):
    """Replays a captured action trace with the same primitives the personas used."""
    for step in trace:
        kind = step.get("kind")
        selector = step.get("selector")
        try:
            if kind == "click" and selector:
                for _ in range(step.get("repeat", 1)):
                    page.click(selector, timeout=1500, force=step.get("force", True), no_wait_after=True)
                    page.wait_for_timeout(step.get("delay_ms", 100))
            elif kind == "fill" and selector:
                page.fill(selector, step.get("value") or "", timeout=1500)
            elif kind == "press":
                key = step.get("key", "Enter")
                if selector:
                    page.press(selector, key)
                else:
                    page.keyboard.press(key)
            elif kind == "force_enable_disabled":
                page.evaluate(\"\"\"() => {{
                    document.querySelectorAll('button:disabled, input:disabled, [aria-disabled="true"], [disabled]').forEach(el => {{
                        el.removeAttribute('disabled');
                        el.removeAttribute('aria-disabled');
                    }});
                }}\"\"\")
            elif kind == "tamper_hidden":
                page.evaluate(\"\"\"() => {{
                    document.querySelectorAll('input[type="hidden"], [readonly]').forEach(el => {{
                        el.removeAttribute('readonly');
                        el.value = 'ADVERSARY_MODIFIED_ADMIN';
                    }});
                }}\"\"\")
            elif kind == "offline":
                page.context.set_offline(bool(step.get("value")))
            elif kind == "throttle":
                cdp = page.context.new_cdp_session(page)
                cdp.send("Network.emulateNetworkConditions", {{
                    "offline": False,
                    "latency": step.get("latency_ms", 1200),
                    "downloadThroughput": 50 * 1024,
                    "uploadThroughput": 20 * 1024,
                }})
        except Exception:
            pass
        page.wait_for_timeout(step.get("delay_ms", 150) if kind != "click" else 50)


def test_reproduce_crash():
    print("⚡ [LOKI REPRO] Starting deterministic crash verification...")
    detected_errors = []

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
{device_setup}

        # Listen for the exact crash
        page.on("pageerror", lambda err: detected_errors.append(str(err)))

        print("⚡ [LOKI REPRO] Navigating to target: {report.target_url}")
        page.goto("{report.target_url}", wait_until="domcontentloaded")

        if REPLAY_TRACE:
            print(f"⚡ [LOKI REPRO] Replaying {{len(REPLAY_TRACE)}} recorded actions from the original session...")
            replay_trace(page, REPLAY_TRACE)
        else:
            print("⚡ [LOKI REPRO] No structured trace captured; falling back to generic burst interaction...")
            buttons = page.query_selector_all("button:visible, input[type=\\'submit\\']:visible")
            for btn in buttons:
                try:
                    for _ in range(5):
                        btn.click(timeout=1000, no_wait_after=True)
                except Exception:
                    pass

        page.wait_for_timeout(1000)
        context.close()
        browser.close()

    if detected_errors:
        print("\\n💥 [LOKI REPRO] CRASH SUCCESSFULLY REPRODUCED!")
        for err in set(detected_errors):
            print(f"  • {{err}}")
        sys.exit(1)
    else:
        print("\\n✔ [LOKI REPRO] No crashes detected. Bug might be resolved.")
        sys.exit(0)

if __name__ == "__main__":
    test_reproduce_crash()
'''